services:
  # chatservice:
  #   container_name: chat
  #   image: chzzk_producer
  #   volumes:
  #     - ./ChzzkChat-main:/app
  #   working_dir: /app
  #   command: ["sleep", "infinity"]

  client:
    container_name: client
    image: client
    volumes:
      - .:/app
    working_dir: /app
    command: ["sleep", "infinity"]
