services:
  client:
    container_name: client
    build: .
    volumes:
      - .:/app
    working_dir: /app
    command: >
      sh -c "aws eks update-kubeconfig --region ap-northeast-2 --name chzzk-eks-cluster && sleep infinity"
    environment:
      # .env (gitignored)
      - AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY
      - AWS_DEFAULT_REGION

  
