apiVersion: v1
kind: Pod
metadata:
  name: jupyter-notebook
  labels:
    app: jupyter-notebook
spec:
  containers:
  - name: jupyter
    image: jupyter/pyspark-notebook:latest
    ports:
    - containerPort: 8888
    command: ["/usr/local/bin/start-notebook.sh"]
    args:
      - "--NotebookApp.token=''"
      - "--NotebookApp.password=''"
---
apiVersion: v1
kind: Service
metadata:
  name: jupyter-service
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-internal: "false"
    # 헬스체크 관련 애노테이션 설정
    service.beta.kubernetes.io/aws-load-balancer-healthcheck-protocol: "HTTP"
    service.beta.kubernetes.io/aws-load-balancer-healthcheck-port: "traffic-port"
    service.beta.kubernetes.io/aws-load-balancer-healthcheck-path: "/lab"
    service.beta.kubernetes.io/aws-load-balancer-healthcheck-interval: "20"
    service.beta.kubernetes.io/aws-load-balancer-healthcheck-timeout: "5"
    service.beta.kubernetes.io/aws-load-balancer-healthcheck-unhealthy-threshold: "2"
    service.beta.kubernetes.io/aws-load-balancer-healthcheck-healthy-threshold: "2"
spec:
  selector:
    app: jupyter-notebook
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8888
  type: LoadBalancer